### ISSUE TITLE
请问按照博客操作仍然报错是为什么？

### ISSUE THREAD

**Issue by HZA2000** [isongxw/Qt-VTK-Demo#1]
D:\code\C_plus_plus_qt_code\TestQt5_9\mainwindow.cpp:27: error: undefined reference to `__imp__ZN22QVTKOpenGLNativeWidget13defaultFormatEb'

报了一大堆这种错误，您能帮忙解决一下吗，十分感谢！

**Comment by isongxw** [comment]
可以参考这个链接：
https://forum.qt.io/topic/104527/facing-error-undefined-reference-to-__imp__zn
